# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d21b91e60bdb84f5e143e8ac9bb4a6362bbeb6eddb8582037ae668d4f62f79197fab769ccd88b6ffe17d6b8c0b72a56fd4ba050409eadfd300c8bb819b39df3b

test:
  secret_key_base: 6c0373ad5aa184c794fa95570873027a37704164cd2aa9d174482deb814f170e6b97de6e028c297ed4f7531e2cb68e4428e18dccd3407d92d7b083ffc7114e52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
